### ISSUE TITLE
Hi , the work is very meaningful,I wonder when will you released the source code

### ISSUE THREAD

**Issue by LIUHUACHENG** [ZhendongWang6/Uformer#1]

**Comment by Lvhhhh** [comment]
+1

**Comment by vinthony** [comment]
Hi, thanks for your attention!

We are still working hard to re-organize the code structure.

Thus, the code might be released in a few weeks (before next month).

**Comment by CCECfgd** [comment]
非常期待能够看到源代码

**Comment by joe0327** [comment]
日常催更![image](https://user-images.githubusercontent.com/5153527/122901042-c12a1500-d37f-11eb-847a-c3195adc77bf.png)

**Comment by Yaowenzhe** [comment]
我也来催更 doge

**Comment by eliver8801** [comment]
日常催更+1。

**Comment by JoshonSmith** [comment]
催更啦，催更啦

**Comment by shiguangliuguo** [comment]
催更~~~

**Comment by ZhendongWang6** [comment]
Thanks for your attention! We are very busy with other works in the last few days. Sorry for the delay of code release. 
And we are going to release the code recently.

**Comment by vinthony** [comment]
Dear all, 

The train/test code has been open-sourced as an initial version.

Thanks for your waiting again.
