### ISSUE TITLE
why dataset is small but performence is sota?

### ISSUE THREAD

**Issue by shiguangliuguo** [ZhendongWang6/Uformer#10]
hi, thanks for your meaningful work 
previous work about Transformer in vision hava a common opinion
which transformer needs huge dataset to feed if you want its performence great

in this work, you just train the network in SIDD patches, which nearly about 9w patches , but other works train their Transformer in nealy 100w. 

so, can you explain this  reason? 
or can i say Transformer actually does not need too many data to feed?

**Comment by vinthony** [comment]
Please check out the recent works in Vision Transformer, like T2T and SwinTransformer. A larger dataset is not necessary for current vision transformer models. Overall,  according to previous works and our experiments, we can train the vision transformer for computer vision tasks on a fair dataset.
