### ISSUE TITLE
this model doesn't provide pre-trained data?

### ISSUE THREAD

**Issue by songbae** [ZhendongWang6/Uformer#12]

**Comment by vinthony** [comment]
please refer to #8

**Comment by vinthony** [comment]
Hi, we have open sourced the uformer16 and uformer32 for SIDD denoising. please see the readme for further detail.

**Comment by amandayeyan** [comment]
> Hi, we have open sourced the uformer16 and uformer32 for SIDD denoising. please see the readme for further detail.

Hi the released uformer16 and uformer32 are based on uformer_B?
