### ISSUE TITLE
How to get unified photo while evaluation?

### ISSUE THREAD

**Issue by parkhy0106** [ZhendongWang6/Uformer#13]
I used the tutorial and got patched inputs but is there any tutorial to get unified results or should I make one of them?

**Comment by vinthony** [comment]
Hi, thanks for your attention to our work.

For SIDD, the evaluation is based on the 256x256 patches following previous methods.

Here, we create another script to test the arbitrary resolution images in `test_in_any_resolution.py`. Please feel free to contact us if you have any questions.

**Comment by parkhy0106** [comment]
OMG!!! I LOVE YOU GUYS!!!
