### ISSUE TITLE
How do you compute Flops of uformer16 and 32?

### ISSUE THREAD

**Issue by leonmakise** [ZhendongWang6/Uformer#16]
I used the same package as your code. (from ptflops import get_model_complexity_info)

And got 2.51 GMac, 5.15 M for Uformer16,  9.98 GMac   20.47 M for Uformer32.

It seems that I need to define some ops in this model. Can you provide a solution or relative code on computing Flops and Params?

Thanks!

**Comment by vinthony** [comment]
We have updated the flops calculation in the model.py

**Comment by leonmakise** [comment]
Thanks for reply! I have tried it, but I got 12.00 G for Uformer16 and 43.86 G for Uformer32, which are a bit higher than origin manuscript. Are those results right?

**Comment by vinthony** [comment]
Yes, originally, we use the `pyflops` for computation. The slightly higher results come from the manual calculation for each operator. The numbers in the paper will be fixed.

**Comment by leonmakise** [comment]
Got that, thanks a lot!
