### ISSUE TITLE
Which SIDD data do you use exactly?

### ISSUE THREAD

**Issue by JZPeterPan** [ZhendongWang6/Uformer#19]
Hi, you use SIDD-Medium sRGB data, right? but there are mirror 1 and mirror 2, so which mirror do you use? and what's the difference of mirror 1 and 2?

**Comment by hanliyao** [comment]
they are the same

**Comment by vinthony** [comment]
solved by about answer.

**Comment by lidong-pig** [comment]
hi。the mirror one can't be down,can you help me?
