### ISSUE TITLE
Why is the SSIM value in this paper different from that in paperswithcode?

### ISSUE THREAD

**Issue by Pocom** [ZhendongWang6/Uformer#28]
Hi, I found that the value of SSIM in your paper (0.970) on SIDD is different and significantly higher than in [paperswithcode](https://paperswithcode.com/sota/image-denoising-on-sidd)(0.959). Your test code uses the `structural_similarity` method to calculate SSIM, using this method I can also get the same result as in your paper, but is this result comparable with other papers?

**Comment by cs-hao** [comment]
Using structural_similarity  may obtain inaccurate results.

**Comment by Pocom** [comment]
> Using structural_similarity may obtain inaccurate results.

Thanks for the reply, so is there any python method to obtain results that can be compared to other methods?

**Comment by gauenk** [comment]
Why would the standard code, namely [structural_similarity from scikit-imag](https://scikit-image.org/docs/dev/auto_examples/transform/plot_ssim.html)e, produce inaccurate results? I would expect some type of explanation or a PR to the structural_similarity to fix their error.
