### ISSUE TITLE
Support arbitrary input resolution?

### ISSUE THREAD

**Issue by vztu** [ZhendongWang6/Uformer#3]
Hi your work is very inspiring! 

I didn't find in your paper on how you apply Uformer during inference. For example, on SIDD, the training patches are 128x128, and evaluation patches are 256x256. Were you directly applying your network on the whole 256x256 patch, or in a sliding window form?  In other words, does Uformer supports arbitrary input resolution?

**Comment by vinthony** [comment]
Hi, thanks for your attention.

The proposed network can be evaluated in any resolution, even the wired resolution. 

For the images in square~(or `X%128==0`), we can directly test the images by producing more windows. 

For the other images, we can test the images via padding the images to square  ` (max(W, H)//128+1) * 128` with an additional mask as input to the transformer, similar to NLP. Then, we mask out the invalided pixels.

For the SIDD, we directly train the network on 128s and test on 256s. We find the larger image will gain better performance comparing with the sliding window solution.
