### ISSUE TITLE
Where is the Modulator in model.py ?

### ISSUE THREAD

**Issue by shinianzhihou** [ZhendongWang6/Uformer#35]
I can't find where the "Modulator" in the paper is implemented in `model.py` code.
Could you please help find it?

**Comment by babbu3682** [comment]
I am also most curious about their third novelty, modulator, but I couldn't find the code.

**Comment by ZhendongWang6** [comment]
Hi, the code of modulator is not included in this version.
We are sorting up the new version of code, and will release it as soon as possible.

**Comment by chenquan-hdu** [comment]
Hi, @ZhendongWang6 
I have the same problem. 
Could you please help find it?

**Comment by ZhendongWang6** [comment]
Hi, thanks for your interest! We have uploaded codes and models. You can find it in model.py of this version.
