### ISSUE TITLE
Deblur pretrain model weight?

### ISSUE THREAD

**Issue by po-sheng** [ZhendongWang6/Uformer#39]
Hi, 

Thanks for your wonderful work of Uformer! 
I'm wondering is there a plan to release the pretrain weight train on GOPRO?
Thank you!

**Comment by ZhendongWang6** [comment]
Hi, thanks for the interest!
We are sorting out codes recently. The weights will be also released.

**Comment by po-sheng** [comment]
Thanks for you prompt reply!

**Comment by gauenk** [comment]
Is there any update on this?
