### ISSUE TITLE
about epochs in training time

### ISSUE THREAD

**Issue by Rookielike** [ZhendongWang6/Uformer#6]
hi friend:
  Uformer is interesting. Paper reports that you train Uformer_16 for 250 epochs with batch size 32 to get 39.66 PNSR in SIDD. So how many iters in training phase？What is PSNR when 40 epochs are trained？ I just want to reproduce this result in a short time

**Comment by vinthony** [comment]
Hi, thanks for your attention.

> So how many iters in the training phase？
This setting is similar to NBNet, with almost 750k iteration.

> What is PSNR when 40 epochs are trained？
almost 39.40 dB around

**Comment by Rookielike** [comment]
thx for reply
