### ISSUE TITLE
The val set of SIDD cannot be downloaded. The URL needs permission.

### ISSUE THREAD

**Issue by leonmakise** [ZhendongWang6/Uformer#7]
The provided link needs permission. **https://drive.google.com/drive/folders/1LzYL4GYH5U40rae_4jvy8kzOtsiMeXFn**
Is that the 'SIDD Benchmark Data'?

**Comment by vinthony** [comment]
Hi, you can download it from here https://drive.google.com/drive/folders/1j5ESMU0HJGD-wU6qbEdnt569z7sM3479
