### ISSUE TITLE
Pertrained Model

### ISSUE THREAD

**Issue by JoshonSmith** [ZhendongWang6/Uformer#8]
Good Job !
Where can we get the pertrained model?
 
Thanks !

**Comment by vinthony** [comment]
Hi, thanks for your attention to our work.

Unfortunately, the pretrained model can not be shared for some reason currently.

We will upload it as soon as possible.

Moreover, you can train our network easily and get similar performance.

**Comment by vinthony** [comment]
Hi, we have open source the uformer16 and uformer32 for SIDD denoising. please see the readme for further detail.
